services:
  postgis:
    image: kartoza/postgis:16-3.4
    platform: linux/arm64
    container_name: stjabah-postgis
    environment:
      POSTGRES_DB: stjabah_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: stjabah@customsolutions.com
      PGADMIN_DEFAULT_PASSWORD: secret

  tileserver:
    image: maptiler/tileserver-gl:latest
    container_name: stjabah-tileserver
    ports:
      - "8081:8081"
    volumes:
      - ./tiles:/data

  valhalla:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    container_name: stjabah-valhalla
    ports:
      - "8002:8002"
    volumes:
      - ./valhalla/custom_files:/custom_files
      - valhalla_tiles:/valhalla/tiles

  backend:
    build: .
    container_name: stjabah-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgis:5432/stjabah_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: secret
      TILESERVER_BASE_URL: http://tileserver:8080
      VALHALLA_BASE_URL: http://valhalla:8002
    ports:
      - "8080:8080"
    depends_on:
      postgis:
        condition: service_healthy

volumes:
  postgis_data:
  valhalla_tiles: